version: "3.8"
services:
  node:
    container_name: "Node_Server"
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    init: true
    depends_on: 
     - mongo
  mongo:
    container_name: "MongoDB_Server"
    build: ./database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  vue:
    container_name: "Nginx_Server"
    build: ./frontend/
    depends_on: 
     - certs
    ports: 
      - "5000:443"
    restart: always